apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: external-resources-server-ingress
  namespace: external-resources
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "1g"
    avp.kubernetes.io/path: "secret/data/apps/nextcloud/prod"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <nextcloud-url> # nextcloud-url (diagon.ally)
    secretName: diagon-ally-tls
  - hosts:
    - <nextcloud-internal-url-styx> # nextcloud-url (styx.myth)
    secretName: styx-myth-tls
  rules:
  - host: <nextcloud-url> # nextcloud-url (diagon.ally)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-external
            port:
              number: 80
  - host: <nextcloud-internal-url-styx> # nextcloud-url (styx.myth)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-external
            port:
              number: 80
---
# Separate Ingress for Nextcloud (HTTP backend) - External Resources Namespace
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nextcloud-ingress
  namespace: external-resources
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    # HTTP backend (default)
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    avp.kubernetes.io/path: "secret/data/apps/nextcloud/prod"
spec:
  tls:
  - hosts:
    - <nextcloud-internal-url> # nextcloud-internal-url (diagon.ally)
    secretName: diagon-ally-tls
  - hosts:
    - <nextcloud-internal-url-styx> # nextcloud-internal-url (styx.myth)
    secretName: styx-myth-tls
  rules:
  - host: <nextcloud-internal-url> # nextcloud-internal-url (diagon.ally)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-external
            port:
              number: 30027
  - host: <nextcloud-internal-url-styx> # nextcloud-internal-url (styx.myth)
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nextcloud-external
            port:
              number: 30027
