apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jellyfin-ingress
  namespace: external-resources
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    # WebSocket support for Jellyfin
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    avp.kubernetes.io/path: "secrets/data/apps/jellyfin/prod"
    nginx.org/server-snippets: |
      proxy_set_header Authorization $http_x_emby_authorization;
    nginx.org/proxy-body-size: "0"
    nginx.org/proxy-read-timeout: "3600"
    nginx.org/proxy-send-timeout: "3600"
    nginx.org/ssl-redirect: "false"

spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - <jellyfin-url-styx>
    secretName: styx-myth-tls
  rules:
  - host: <jellyfin-url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-external
            port:
              number: 30013
  - host: <jellyfin-url-styx>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jellyfin-external
            port:
              number: 30013
